name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env: 
      ARM_CLIENT_ID: "18625e5d-e15d-4c63-b145-96f09f3f5a65"
      ARM_CLIENT_SECRET: "gwj8Q~sAzYoHcD~t6H5uTn9mQuWwL6D~ZLkYNcpY"
      ARM_SUBSCRIPTION_ID: "39c87760-f7b4-4479-ba4c-a0ed22bc35e2"
      ARM_TENANT_ID: "4f490be5-b518-483a-99f6-90b580ae0cb5"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
        
    
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: |
        cd terraform/
        terraform init

    - name: Terraform Validate
      id: validate
      run: |
        cd terraform/
        terraform validate -no-color

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: |
        cd terraform/
        terraform plan -no-color -input=false
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform/
        terraform apply -auto-approve -input=false